name: 'PBIX Deserializer'
description: 'Deserializes PBIX Files into json files for easier version control'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v12
      with:
        separator: ","
    - name: Power BI VC Utils
      uses: nathangiusti/Power-BI-VC-Utils@v2.4
      with:
        files: ${{ steps.changed-files.outputs.all_modified_files }}
        separator: ","
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Reformatted files for VC
